DomainScraper/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("diary/", include('home.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = "diary"
urlpatterns = [
    path("", views.index, name="index"),
    path("page/create/", views.page_create, name="page_create"),
    path("pages/", views.page_list, name="page_list"),
    path("pages/<uuid:id>/", views.page_detail, name="page_detail"),
    path("pages/test/", views.test_view, name="test_view"),
]

home/models.py
from django.db import models
import uuid

class Page(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
    title = models.CharField(max_length=100, verbose_name="タイトル")
    body = models.TextField(max_length=2000, verbose_name="本文")
    page_date = models.DateField(verbose_name="日付")
    picture = models.ImageField(upload_to="diary/picture/", blank=True, null=True, verbose_name="写真")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")

    def __str__(self):
        return self.title

home/forms.py
from django.forms import ModelForm
from .models import Page

class PageForm(ModelForm):
    class Meta:
        model = Page
        fields = ["title", "body", "page_date", "picture"]

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import PageForm
from .forms import Page
from datetime import datetime
from zoneinfo import ZoneInfo


class IndexView(View):
    def get(self, request):
        datetime_now = datetime.now(
            ZoneInfo("Asia/Tokyo")
        ).strftime("%Y年%m月%d日 %H:%M:%S")
        return render(request, "home/index.html", {"datetime_now": datetime_now})
    
class PageCreateView(View):
    def get(self, request):
        form = PageForm()
        return render(request, "home/page_form.html", {"form": form})
    
    def post(self, request):
        form = PageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("diary:index")
        return render(request, "home/page_form.html", {"form": form})
    
class PageListView(View):
    def get(self, request):
        page_list = Page.objects.order_by("page_date")
        return render(request, "home/page_list.html", {"page_list": page_list})
    
class PageDetailView(View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        return render(request, "home/page_detail.html", {"page": page})
    
class TestView(View):
    def get(self, request):
        return render(request, "home/test.html")
        


index = IndexView.as_view()
page_create = PageCreateView.as_view()
page_list = PageListView.as_view()
page_detail = PageDetailView.as_view()
test_view = TestView.as_view()

home/templates/base/diary_base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>home</title>
    </head>
    <body>
        <h1><a href="{% url 'diary:index' %}">初めてのDjango日記</a></h1>
        {% block body%}
        {% endblock %}
    </body>
</html>

home/templates/home/index.html
{% extends "base/diary_base.html" %}
{% block body%}

<p>{{ datetime_now }}</p> 
<br>
<a href="{% url 'diary:page_create' %}">日記を書く</a>
<br>
<a href="{% url 'diary:page_list' %}">ページ一覧</a>


{% endblock %}  

home/templates/home/page_detail.html
{% extends "base/diary_base.html" %}
{% block body%}

<h2>{{ pate.title }}</h2>
<div>{{ page.page_date }}</div>
<div>{{ page.body | linebreaksbr }}</div>
{% if page.picture %}
    <img src="{{ page.picture.url }}" alt="写真">
{% endif %}

{% endblock %}  

home/templates/home/page_form.html
{% extends "base/diary_base.html" %}
{% block body%}
<h2>日記を書く</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">保存</button>
</form>
{% endblock %}

home/templates/home/page_list.html
{% extends "base/diary_base.html" %}
{% block body%}

<ul>
    {% for page in page_list %}
        <li>{{ page.page_date }}: <a href="{% url 'diary:page_detail' page.id %}">{{ page.title }}</a></li>
    {% empty %}
        <div>日記のページが1つもありません。</div>
    {% endfor %}
</ul>
{% endblock %}  

home/templates/home/test.html
{% extends "base/diary_base.html" %}
{% block body%}

<h1>表示成功</h1>

{% endblock %}  